# Generated by Django 4.2 on 2023-04-09 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getotp', '0002_alter_otprequest_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 32, 47, 114936, tzinfo=datetime.timezone.utc)),
        ),
    ]
