# Generated by Django 4.2 on 2023-04-09 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getotp', '0003_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 34, 7, 306819, tzinfo=datetime.timezone.utc)),
        ),
    ]
